<a href="https://colab.research.google.com/github/datagrad/1.ML/blob/main/Random_Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import sklearn as sk
import numpy as np
import scipy as sp
from sklearn import tree
from sklearn.metrics import confusion_matrix

# Data Importing

In [2]:
#Importing dataset
car_train=pd.read_csv("https://raw.githubusercontent.com/venkatareddykonasani/Datasets/master/Car_Accidents_IOT/train.csv")
car_test=pd.read_csv("https://raw.githubusercontent.com/venkatareddykonasani/Datasets/master/Car_Accidents_IOT/test.csv")

In [3]:
features=list(car_train.columns[1:])
X_train=car_train[features]
y_train=car_train['Fatal']

# Decision Tree

In [4]:
###buildng Decision tree on the training data ####
clf = tree.DecisionTreeClassifier(max_depth=6)
clf.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=6)

## Decision Tree Results

In [5]:
#####predicting on test data ####
tree_predict_train=clf.predict(car_train[features])
tree_predict=clf.predict(car_test[features])

########Train Data Validation
cm1 = confusion_matrix(car_train[['Fatal']],tree_predict_train)
print("Confusion Matrix for Train data \n", cm1)
total1=sum(sum(cm1))
accuracy_tree=(cm1[0,0]+cm1[1,1])/total1
print("Accuracy of Train data \n", accuracy_tree)

########Test Data Validation
cm1 = confusion_matrix(car_test[['Fatal']],tree_predict)
print("Confusion Matrix for test data \n", cm1)
total1=sum(sum(cm1))
accuracy_tree=(cm1[0,0]+cm1[1,1])/total1
print("Accuracy of test data \n", accuracy_tree)


Confusion Matrix for Train data 
 [[4940 1376]
 [ 688 8105]]
Accuracy of Train data 
 0.8633926798596863
Confusion Matrix for test data 
 [[2982  910]
 [ 393 4780]]
Accuracy of test data 
 0.8562603419746276


# Random Forest

In [6]:
from sklearn.ensemble import RandomForestClassifier
forest=RandomForestClassifier(n_estimators=20, max_features=4, max_depth=6)
# n_estimators - Trees - As high as possible
# max_features - p - low ==>(sqrt(t))
# max_depth - Slightly higher than single tree
forest.fit(X_train,y_train)

RandomForestClassifier(max_depth=6, max_features=4, n_estimators=20)

## Random Forest Results

In [7]:
#####predicting on test data ####
Forest_predict_train=forest.predict(car_train[features])
Forest_predict=forest.predict(car_test[features])

########Train Data Validation
cm1 = confusion_matrix(car_train[['Fatal']],Forest_predict_train)
print("Confusion Matrix for Train data \n", cm1)
total1=sum(sum(cm1))
accuracy_tree=(cm1[0,0]+cm1[1,1])/total1
print("Accuracy of Train data \n", accuracy_tree)

########Test Data Validation
cm1 = confusion_matrix(car_test[['Fatal']],Forest_predict)
print("Confusion Matrix for test data \n", cm1)
total1=sum(sum(cm1))
accuracy_tree=(cm1[0,0]+cm1[1,1])/total1
print("Accuracy of test data \n", accuracy_tree)


Confusion Matrix for Train data 
 [[4750 1566]
 [ 536 8257]]
Accuracy of Train data 
 0.860877622609041
Confusion Matrix for test data 
 [[2903  989]
 [ 349 4824]]
Accuracy of test data 
 0.8523993381136238
